### PR TITLE
feat(settings): entry-point configuration providers

### LINKED ISSUE #915: RFE: Set the default Release in RPM builds to RelWithDebInfo
Hello.

Recently, with @hrnciar we discovered the Fedora RPM build of rapidfuzz fails because the debuginfo could not be found.

I've searched why that is possible and found some information in https://github.com/scikit-build/scikit-build-core/issues/875

In Fedora, we found our own CFLAGS (and CXXFLAGS) and they include (amongst others) `-O2` and `-g`. I don't know exactly if the build type as explained in https://stackoverflow.com/a/59314670/1839451 overrides those flags or not, but I know at least this:

 - The default build type in scikit-build-core appears to be Release.
 - When it is Release, the built ELFs are stripped of debuginfo (and RPM builds in Fedora fail).
 - Manually setting the build type to RelWithDebInfo fixes the problem.

Hence I was wondering if it was acceptable for you to **set the default build type to RelWithDebInfo when RPM build is detected**. I completely understand if this is not a territory you want to go to -- we can certainly patch our RPM package of scikit-build-core to do this if you are not interested.

The detection should be possible to do like this:

```python
    build_type: str = "Release" if "RPM_BUILD_ROOT" not in os.environ else "RelWithDebInfo"
```

I don't know if this can be here:

https://github.com/scikit-build/scikit-build-core/blob/f0ae31922ff802b179fce3327a9c93ff65934a23/src/scikit_build_core/settings/skbuild_model.py#L64

Or if it needs to be handled similarly to

https://github.com/scikit-build/scikit-build-core/blob/8380c9e613e9ee06bf28ff3897b80f502e4ca6c8/src/scikit_build_core/settings/skbuild_read_settings.py#L230-L234

Let me know if something like this would be acceptable to you. Thanks.

### LINKED ISSUE #1301: Add a static file as potential source of configuration
There should be an older issue about brainstorming how to configure some initial config files to be used during the Fedora builds (primary usage there is to opt-out of debug symbol stripping). I am now thinking maybe it should be on scikit-build-core side instead (putting them in the rpm build system would be quite a voodoo magic)

### Proposal: expose a `scikit-build-core.config` entry-point

The idea here is that the distro (or user) can define a common dependency that is automatically co-installed at build time (or opt-in pyproject.toml), and scikit-build-core would then read the entry-point and try to get the configuration file(s) from there.

This would serve as the 2nd lowest priority configuration (just above defaults) for the configuration sources.

Don't know if it would be useful for the users also, but technically they can make use of this as well. One benefit of such an approach is that it can be very localized on when it is applied.

Going from entry-point to configuration file, I am not sure what format to choose. Could make it point to a specific variable that has the name/path of the configuration file. Format wise I would say to reuse the toml handler and only support that format.

### Other considerations

Some other approaches would be to search for commonly defined paths like `/etc`. But this has the complexity of keeping track of various path conventions, and being harder for the user to opt-out

### PR DESCRIPTION
**Pull request by henryiii**
This is quite powerful, not sure I like giving out this kind of power. :)

:robot: _AI text below_ :robot:

Closes #1301, closes #915.

## What

Adds two entry-point groups so an installed package can contribute scikit-build-core configuration to **every** build in the environment — aimed at Linux distros (Fedora) that need to set build defaults for all packages without patching each `pyproject.toml`.

A provider is a callable returning a `[tool.scikit-build]`-shaped **dict**, injected as a new `TOMLSource` in the existing `SourceChain`. This reuses all of the precedence / dict-merge / validation / `[[overrides]]` machinery — no new precedence logic — and structurally answers the "override vs. defaults?" question raised in #1301.

## Two groups select the precedence level

The **group** picks the level; the entry-point name is arbitrary (providers in a group are applied in sorted name order, earlier name wins):

```toml
[project.entry-points."scikit-build-core.config.default"]
my-distro = "my_distro_config:config"
```

```python
def config(*, state, env):  # may also be zero-arg
    return {"cmake": {"build-type": "RelWithDebInfo"}, "install": {"strip": False}}
```

| highest → lowest | |
|---|---|
| `SKBUILD_*` env vars | always win (user escape hatch) |
| `-C` / config-settings | |
| `scikit-build-core.config.override` providers | above pyproject.toml |
| `extra_settings` (hatchling) | |
| `pyproject.toml` | |
| `scikit-build-core.config.default` providers | below pyproject.toml, above defaults |
| built-in defaults | |

## Fixes #915

Because the table can include `[[overrides]]` and the override engine already matches `if.env.<VAR>`, a distro provider applies debug-friendly defaults only inside an RPM build:

```python
def config(*, state, env):
    return {"overrides": [{
        "if": {"env": {"RPM_BUILD_ROOT": True}},
        "cmake": {"build-type": "RelWithDebInfo"},
        "install": {"strip": False},
    }]}
```

Opt out of all providers with `SKBUILD_NO_ENTRYPOINT_CONFIG=1`.

## Changes

- **`settings/_load_entrypoint_config.py`** (new) — `load_config_providers()`: discovers both groups, sorts each by name (deterministic), calls each provider (`(state, env)` or zero-arg), returns `(level, name, table)` tuples (overrides first, then defaults).
- **`settings/skbuild_read_settings.py`** — wires providers into `toml_srcs` (insert for `override`, append for `default`), runs `process_overrides` per table, strips `minimum-version` (ep config is environment policy, not project semantics), honors the opt-out env var, and rebuilds `print_suggestions` source-naming via a parallel `_toml_src_names`.
- **`_compat/importlib/metadata.py`** — made the `<3.10` `entry_points` shim robust to the modern selectable object (fixes test failures my code newly exercises when tests simulate Python 3.9).
- **`tests/test_entrypoint_config.py`** (new) — both levels, dict merge, env-matched overrides (#915), opt-out, override-only rejection, suggestions naming, zero-arg providers, sorted-name determinism, `minimum-version` stripping.
- **`docs/configuration/entrypoint_config.md`** (new) + toctree.

## Notes for review

- No changelog entry: that file is per-release/PR-numbered (generated at release), so a manual entry seemed out of place.
- **Design choice to confirm:** `override` is placed *above* `extra_settings` (hatchling's injected config), on the reasoning that distro environment policy should beat project-author static config regardless of frontend. Easy to flip if you'd prefer it below.

### CODE REVIEW

**Comment by henryiii** [comment]
@LecrisUT could you take a look?

**Comment by henryiii** [comment]
I've merged so I can do some reviews with Fable, feel free to review if needed, though.

File: docs/configuration/entrypoint_config.md [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+
+def config(*, state, env):
+    return {
+        "cmake": {"build-type": "RelWithDebInfo"},
+        "install": {"strip": False},
+    }
+```
+
+The callable may also take no arguments; `state` (the build state, e.g.
+`"wheel"`) and `env` (the environment mapping) are passed when accepted.
```
Comment (LecrisUT) [inline docs/configuration/entrypoint_config.md:24]: This could be messy, IMO we should support only one method where the user defines it as `config(**kwargs)` when they do not need the arguments. This would allow it to be future compatible as well if ever we need to add another argument.

File: docs/configuration/entrypoint_config.md [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+
+It is registered under one of two groups; the **group** selects the precedence
```
Comment (LecrisUT) [inline docs/configuration/entrypoint_config.md:26]:
```suggestion
The entry-point is registered under either `scikit-build-core.config.default` or ``scikit-build-core.config.override` which select the precedence level. The entry-point's name is arbitrary and has no effect. 
```

Was confusing reading it at first, couldn't get what the group was referring to

File: docs/configuration/entrypoint_config.md [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+1. `SKBUILD_*` environment variables
+2. `-C`/config-settings
+3. `override` entry-point providers
+4. extra settings (build-frontend plugins, e.g. hatchling)
+5. `pyproject.toml`
+6. `default` entry-point providers
+7. built-in defaults
+
+A package may register providers in both groups, and the entry-point name is
+free-form. When several providers are registered in the same group, they are
```
Comment (LecrisUT) [inline docs/configuration/entrypoint_config.md:62]:
```suggestion
A package may register providers in both groups.
When several providers are registered in the same group, they are
```
Already covered previously

File: src/scikit_build_core/settings/skbuild_read_settings.py [hunk 4]
```diff
@@ -324,6 +328,39 @@ def __init__(
...
+        # SKBUILD_NO_ENTRYPOINT_CONFIG.
+        if not strtobool(environ.get("SKBUILD_NO_ENTRYPOINT_CONFIG", "")):
+            override_index = 0
+            for level, ep_name, ep_table in load_config_providers(
+                state=state, env=environ
+            ):
+                ep_skb = copy.deepcopy(ep_table)
+                ep_matched, ep_overridden = process_overrides(
+                    ep_skb, state=state, env=env, retry=retry
+                )
```
Comment (LecrisUT) [inline src/scikit_build_core/settings/skbuild_read_settings.py:349]: Note that because this is operating on the same table as the settings, not the `tool.scikit-build` one, `append`/`prepend` overrides would likely not have the expected effect because these are handled by the `SourceChain` merger, not the `process_overrides`.

But I don't think we have a good way to handle this now, and would just put a note to handle this in some refactoring of these.

**Review by LecrisUT — COMMENTED** [review]
Looks fine to me, only documentation improvements are actionable atm.

We should really clean up the override code. It's growing into quite the monster. Not for 1.0 though, there's enough on the plate for it and this is only for our and contributor's convenience.

File: docs/configuration/entrypoint_config.md (hunk 1 above)
Comment (henryiii) [reply docs/configuration/entrypoint_config.md:24]: That's exactly the way this works. It's like fixtures in pytest: you request a parameter by name.

Comment (LecrisUT) [reply docs/configuration/entrypoint_config.md:24]: But implementation wise it would not work right? Like you cannot request only `state` without having a catch-all, or am I missing something?
```python
        try:
            table = func(state=state, env=env)
        except TypeError:
            table = func()
```

Edit: a quick test
```python
>>> def func(*, state):
...     print("hi")
... try:
...     func(state=1, env=2)
... except TypeError:
...     func()
Traceback (most recent call last):
  File "<input>", line 4, in <module>
TypeError: func() got an unexpected keyword argument 'env'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 6, in <module>
TypeError: func() missing 1 required keyword-only argument: 'state'
```

Comment (henryiii) [reply docs/configuration/entrypoint_config.md:24]: Ahh, you were looking at the implementation? Yes, this was broken, it was fixed in the general review, in #1424.
